### ISSUE TITLE
I tried for 4 hours the code is not working. Please fix it 

### ISSUE THREAD

**Issue by aertist** [thoppe/DeepMDMA#1]
Please tell the super exact environments for the code to work. Thanks 😀

**Comment by thoppe** [comment]
Hi @aertist it's really hard to figure out what "not working" means. Give me an error message and I can work with it! When I wrote this, I tested it with python 3.6.0 and used the requirements as listed. I didn't freeze the reqs. some maybe there was some version shift. Let me know what the problem is, and if you don't give me a lot of detail I can't help.

**Comment by aertist** [comment]
There are several of them. Can you tell the versions of tensorflow, scipy, lucid you used?

its incompatible with TF2 I think.
(i tried with an older TF version 1.14.0 but no luck
also I had to install scipy==1.2.0  because `imsave` is deprecated in new scipy versions.
I'm using python 3.6 in google collab.

When i use TF version 1 it gives this error:

`Start {'--help': False,
 '--model_size': '200',
 '--n_training': '1024',
 '--output_image_size': '600',
 '<channel>': 'mixed4a_3x3_pre_relu',
 '<k>': '25'}
Loading model
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/lucid/misc/io/reading.py:126: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/lucid/misc/io/reading.py:126: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.`

i used this command to import tensorflow: `import tensorflow.compat.v1 as tf` instead of just `import tensorflow as tf`

And when I use TF2.0
It is giving me error:

`Traceback (most recent call last):
  File "render_activations.py", line 23, in <module>
    from tensorflow.contrib import slim
ModuleNotFoundError: No module named 'tensorflow.contrib'` (as it is deprecated)

Then I switched to TFv1 within TF 2.0 by this command: `%tensorflow_version 1.x`
And now it says:

 `Start {'--help': False,
 '--model_size': '200',
 '--n_training': '1024',
 '--output_image_size': '600',
 '<channel>': 'mixed4a_3x3_pre_relu',
 '<k>': '25'}
Loading model
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/lucid/misc/io/reading.py:126: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/lucid/misc/io/reading.py:126: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.
WARNING:tensorflow:From render_activations.py:92: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.
WARNING:tensorflow:From render_activations.py:92: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.`

So i went ahead and changed `tf.train.AdamOptimizer` to `tf.compat.v1.train.AdamOptimizer` in render_activations.py line 92
then I got this error: 

`Start {'--help': False,
 '--model_size': '200',
 '--n_training': '1024',
 '--output_image_size': '600',
 '<channel>': 'mixed4a_3x3_pre_relu',
 '<k>': '25'}
Loading model
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/lucid/misc/io/reading.py:126: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/lucid/misc/io/reading.py:126: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.`

Heres is a link to that ipython notebook. [DeepMDMA](https://colab.research.google.com/drive/1mpccPsglIeWidyzhUPv9HE8QtwVLyJ3U#scrollTo=GgNslsHy3izx)

And I'm stuck here.

**Comment by thoppe** [comment]
Hi, so sorry it didn't work on the first run. It was definitely a case of version creep, the main cultript being tensorflow. I'm not sure what version I used two years ago, but I found some dependencies that work for python 3.6.1. I've updated the requirements file, but you can see them here too:

```
# Core numerical libs
numpy==1.19.4
scipy==1.5.4
imageio==2.9.0
pillow==8.0.1

# Deep learning
tensorflow==1.14.0
lucid==0.3.8


# Audio libs
librosa==0.8.0

# Helper libs
tqdm==4.55.0
docopt==0.6.2
```

I can verify that a fresh install of 3.6.1 with these deps works on my machine.

**Comment by thoppe** [comment]
There are a _ton_ of warnings, but it does seem to work still. Your error messages were helpful, it got me looking in the right direction.
