### ISSUE TITLE
Can you add gpu support?

### ISSUE THREAD

**Issue by aertist** [thoppe/DeepMDMA#3]
First off this is a great tool. But can you make a yt tutorial on how to use this and can you add the gpu support?
Since its using tenosrflow it should be easy to add gpu support?
Here's a colab notebook [link](https://colab.research.google.com/github/aertist/DeepMDMA/blob/master/DeepMDMA.ipynb)

**Comment by thoppe** [comment]
Thanks, glad you like it! I don't have time to make a YT tutorial (those take a lot of effort!) as this project is archived for me. GPU support should be easy to incorporate, I'm surprised it doesn't work directly out of the box in Colab. It works on my PC, so maybe it's an issue with Lucid. 

If you figure it out, send it a PR and I'll be happy to merge it in!
